# Form implementation generated from reading ui file 'CycleGAN_NCNN_Widget.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        self.widget_input_img = QtWidgets.QWidget(parent=Form)
        self.widget_input_img.setGeometry(QtCore.QRect(120, 140, 256, 256))
        self.widget_input_img.setObjectName("widget_input_img")
        self.graphicsView_input_img = QtWidgets.QGraphicsView(parent=self.widget_input_img)
        self.graphicsView_input_img.setGeometry(QtCore.QRect(0, 0, 256, 256))
        self.graphicsView_input_img.setObjectName("graphicsView_input_img")
        self.widget_output_img = QtWidgets.QWidget(parent=Form)
        self.widget_output_img.setGeometry(QtCore.QRect(510, 140, 256, 256))
        self.widget_output_img.setObjectName("widget_output_img")
        self.graphicsView_output_img = QtWidgets.QGraphicsView(parent=self.widget_output_img)
        self.graphicsView_output_img.setGeometry(QtCore.QRect(0, 0, 256, 256))
        self.graphicsView_output_img.setObjectName("graphicsView_output_img")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(110, 20, 501, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_upload = QtWidgets.QPushButton(parent=Form)
        self.pushButton_upload.setGeometry(QtCore.QRect(120, 450, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_upload.setFont(font)
        self.pushButton_upload.setObjectName("pushButton_upload")
        self.pushButton_convert = QtWidgets.QPushButton(parent=Form)
        self.pushButton_convert.setGeometry(QtCore.QRect(360, 450, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_convert.setFont(font)
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.pushButton_download = QtWidgets.QPushButton(parent=Form)
        self.pushButton_download.setGeometry(QtCore.QRect(600, 450, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_download.setFont(font)
        self.pushButton_download.setObjectName("pushButton_download")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CycleGAN-NCNN"))
        self.label.setText(_translate("Form", "CycleGAN-NCNN"))
        self.pushButton_upload.setText(_translate("Form", "Upload"))
        self.pushButton_convert.setText(_translate("Form", "Convert"))
        self.pushButton_download.setText(_translate("Form", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
